services:
  finance-dashboard:
    image: finacr.azurecr.io/finance-dashboard:1.0.5
    secrets:
      - db_connection
      - sftp_password
    environment:
      - API_KEY_FILE=/run/secrets/db_connection
      - IMPORT_SFTP_USER=import_user

secrets:
  db_connection:
    external: true
  sftp_password:
    external: true
