version: "3.9"

services:
  api:
    image: myregistry.azurecr.io/hybrid-api:1.0.0
    networks:
      - hybrid-net
    deploy:
      replicas: 3

  worker:
    image: myregistry.azurecr.io/hybrid-worker:1.0.0
    networks:
      - hybrid-net
    deploy:
      replicas: 2

networks:
  hybrid-net:
    external: true
